language: c
os:
        - linux
        - osx
compiler:
        - gcc
        - clang

notifications:
        email:
                on_success: change
                on_failure: always

before_install:

install:
        - sudo apt-get install libgtest-dev libgtest

before_script:
        - sudo ldconfig

script:
        - make all
        - make test
